# Computação científica e análise de dados - 2023.2
# **Lista 2:** Posto, fatoração LU e sistemas lineares
## **Autor:** Artur Henrique Teixeira do Amaral
## **DRE:** 122032113

In [1]:
using LinearAlgebra

## **Ex. 1**

In [60]:
# 1-a)

# A matriz de usuários por filmes possui a seguinte interpetração:
# Cada linha representa um usuário, cada coluna representa um filme.
# O número em uma posição qualquer é o quanto aquele filme coincide com o perfil daquele usuário.
# Quanto MAIS PRÓXIMO DE ZERO o número, mais o usuário tem compatibilidade com o filme.
# O valor é o somatório da diferença absoluta entre preferência do usuário e genêro do filme.

UserFeatureMatrix = 
   [0.9 0.1
    0.8 0.2
    0.3 0.7
    0.6 0.4
    0    1]

MovieFeatureMatrix =
   [0.9 0.1
    0.1 0.9
    0.5 0.5
    0    1
    0.2 0.8]


UserMovieMatrix = zeros( length(UserFeatureMatrix[:,1]),
                        length(MovieFeatureMatrix[:,1]))

for user in 1:length(UserFeatureMatrix[:,1])
    for movie in 1:length(UserMovieMatrix[:,1])
        UserMovieMatrix[user, movie] =  abs(UserFeatureMatrix[user, 1] - MovieFeatureMatrix[movie, 1]) + # preferencia por romance do usuário - valor de romance no filme...
                                        abs(UserFeatureMatrix[user, 2] - MovieFeatureMatrix[movie, 2])
    end
end 

display(UserMovieMatrix)

5×5 Matrix{Float64}:
 0.0  1.6  0.8  1.8  1.4
 0.2  1.4  0.6  1.6  1.2
 1.2  0.4  0.4  0.6  0.2
 0.6  1.0  0.2  1.2  0.8
 1.8  0.2  1.0  0.0  0.4

In [61]:
# 1-b)
# Cada linha da matriz representa um usuário, em que cada valor é o gosto por um filme.
# Ao calcular a distância euclidiana entre duas linhas quaisquer, teremos uma medida de quão parecidos são dois usuários.
# Quanto menor for a distância entres dois usuários, mas parecidos entre se eles são.

leastDistance = 1000000000000 # Distancia suficientemente grande para iniciar o algoritmo de encontrar o menor número.
firstUser = 0
secondUser = 0

for firstUserIdx in 1:length(UserMovieMatrix[:,1])
    for secondUserIdx in 1:length(UserMovieMatrix[:,1])
        if firstUserIdx != secondUserIdx # Ignora-se a comparação de um usuário com ele mesmo
            # Norma entre dois usuários quaisquer
            n = norm( UserMovieMatrix[firstUserIdx,:] - UserMovieMatrix[secondUserIdx,:]) 
            
            # Caso uma distancia menor que a atual seja encontrada, atualiza-se a menor distancia e quem são os usuários que a representam.
            if n < leastDistance
                leastDistance = n
                firstUser = firstUserIdx
                secondUser = secondUserIdx
            end
            
            # println(firstUserIdx, " ", secondUserIdx, " ", n)
        end
    end
end

print(firstUser, " ", secondUser)

# Pela execução do código, conclui-se que os usuários mais parecidos entre si são A e B (Índices 1 e 2, respectivamente.)

1 2

## **Ex. 2**

**(a)** Significa que eles não possuem nenhum sintoma em comum.

**(b)** Significa que esses dois sintomas não estão presentes simultaneamente em um mesmo paciente.

**(c)** Significa que eles possuem exatamento a mesma combinação de sintomas.

**(d)** Significa que a ocorrência destes dois sintomas é igual em todos os pacientes.

## **Ex. 3**

**(a)** Nomenado as colunas da matriz A como ai, onde i é o número da coluna, podemos escrevê-la  como:

**A = [a1 a2 a3 a4 a5]**

Observam-se as seguintes relações:

Sendo **v = [-1 -10 -1 -1]**

* **a1 = a1**
* **a2 = 5*a1**
* **a3 = 10*a1**
* **a4 = a1*v**  *# Obs: a posição dos vetores não está rigorosamente certa. Interprete como o produto que resulta na coluna a4.*
* **a5 = a1*0**

Isto é, as colunas de A podem ser escritas como produtos de apenas dois vetores: a1 e v.
Isso nos sugere que o posto da matriz A é 2.

**(b)** Seguindo o mesmo raciocínio, as colunas da matriz A serão nomeadas ai, de forma que:

**A = [a1 a2 a3 a4 a5]**

Podemos observar as seguintes relações entre as colunas:

* **a1 = a1**
* **a2 = a2**
* **a3 = a3**
* **a4 = 100*a3**
* **a5 = a1 + 10*a2**

Como as 5 colunas de podem ser reescritas como combinações lineares de três destas colunas, isso nos sugere que o posto desta matriz é 3.

## **Ex. 4**

``` Julia
A = [2 10 20 200 -10
-3 -15 -30 -300 15
5 25 50 500 -25
7 35 70 700 -35]
```

A matriz A é posto 1, podendo ser representada pelo produto das matrizes B e C tal que:

``` Julia
A = B*C

B = [2
    -3
    5
    7]

C = [1 5 10 100 -5]

```

Interpretando esses dados, podemos considerar os valores na matriz B como o quanto aquele usuário gosta de comédia. Os valores na matriz C podem ser interpretados como o quanto cada filme é de comédia. 

Dessa forma, ao realizar a multiplicação das duas matrizes, por exemplo, se um usuário que possui uma preferência negativa por comédia encontrar um filme muito de comédia, sua avaliação será muito negativa, ao passo de que, se o filme for só um pouco de comédia, será pouco negativa e, se não for de comédia (negativo), sua avaliação ficará positiva.

## **Ex. 5**

**(a)**

Podemos representar a bandeira da Grécia como uma matriz G, onde 0 representa a cor branca e 1 representa a cor azul.

É possível observar que todas as colunas dessa matriz repetem basicamente três padrões, que são:

``` Julia
g1 = [
    1
    1
    0
    1
    1
    0
    1
    0
    1
]

que representa a coluna mais a esquerda, que possui listrado horizontal e a parte do quadrado que possui azul predominante.

g2 = [
    0
    0
    0
    0
    0
    0
    1
    0
    1
]
    
que representa a única coluna que possui uma faixa branca na vertical.

g3 = [
    1
    0
    1
    0
    1
    0
    1
    0
    1
]
    
que representa todas as colunas mais à direita, o listrado horizontal.
```

Como podemos interpretar o posto de uma matriz como o número de colunas linearmente independentes dela, concluimos que a bandeira da Grécia possui posto 3.

**(b)** Alemanha e Colômbia

**(c)** Dinamarca e Finlândia

**(d)** França e Itália

## **Ex. 6**

O sorriso pode ser representado como uma matriz 5x5, com os valores 0, 1 e 2 representando suas cores. 

A referência tomada será do mais claro para o mais escuro, logo 0 equivale a cor branca, 1 ao cinza e 2 ao preto.

Logo, a matriz do sorriso é S tal que:

``` Julia
S = [
0 2 0 2 0
0 2 0 2 0
0 0 1 0 0
2 0 0 0 2
0 2 2 2 0
]
```

e suas colunas chamam-se si, tal que:

**S = [s1 s2 s3 s4 s5]**

Intuitivamente, podemos pensar que, como o sorriso é simétrico, podemos armazená-lo sem as colunas 4 e 5 sem perder informação.

Aplicando o mesmo raciocínio do exercício 3, podemos escrever as colunas do sorriso como:

* **s1 = s1**
* **s2 = s2**
* **s3 = s3**
* **s4 = s2**
* **s5 = s1**

Como podemos escrever as 5 colunas da matriz a partir de combinações de apenas 3 colunas, podemos inferir que o posto do sorriso é 3.

## **Ex. 7**

Seja a matriz:
``` Julia
A = [1 2
    1 3]
```

Podemos somar menos uma vezes a primeira linha à segunda linha, e atribuir esse resultado à própria segunda linha, obtendo a matriz:
``` Julia
U = [1 2
    0 1]
```

A matriz triangular inferior que desfaz essa operação é L, tal que:

``` Julia
L = [1 0
    1 1]

A = L*U
```

A obtenção da matriz L foi realizada na tentativa e erro, sem uso de fórmulas da decomposição LU.


## **Ex. 8**

**Notação:**

Ao aplicar a eliminação gaussiana, utilizarei a seguinte notação:
``` Julia
Li <- a*Li + b*Lj
```
Significa que o novo valor atribuído à linha **Li** é **a** vezes **Li** mais **b** vezes **Lj**.

---

**(a)**

Dada a matriz 

``` Julia
A = [2 1 1
    4 3 3
    6 7 10]
```

Seguem os passos da eliminação gaussiana para obtenção da matriz triangular superior U:

``` Julia
L2 <- L2 - 2*L1
L3 <- L3 - 3*L1

Obtendo:

A = [2 1 1
    0 1 1
    0 4 7]

Por fim:

L3 <- L3 -4*L2

U = [2 1 1
    0 1 1
    0 0 3]
```

Dada essa matriz U, obtida pelo processo de eliminação gaussiana, realizei um procedimento de tentativa e erro na mão para encontrar a matriz L.
Nesse processo, descobri que os valores que ocupam os lugares dos coeficiente **a** e **b** da minha notação aparecem na matriz L, seguindo algum padrão. 

Segue a matriz L:

``` Julia

L = [1 0 0
    2 1 0
    3 4 1]

tal que:

A = L*U

```

**(b)**

Seja o vetor x pertencente a R3, tal que x = (x1, x2, x3).

Podemos representar a equação dada como o sistema linear:

```Julia
2*x1 + x2 + x3 = 2
       x2 + x3 = 4
            x3 = 6
```
Aplicando a substituição reversa, achamos que

```
x = (-1, -2, 6)
```

## **Ex. 9** (DOING)

In [79]:
A = [2 1 1
4 5 4
6 15 16]

display(A)

# 9-a)
# Uma opção de matrix de posto 1 que aproxima A é uma matriz A1 cujas colunas são todas iguais à segunda coluna de A.

A1 = [1 1 1
5 5 5
15 15 15]

norm(A-A1)

# 9-b)

# Implementação da decomposição LU fornecida pelo professor no classroom.
function LU(A)
    n,n=size(A)
    L=zeros(n,n)
    U=zeros(n,n)
    for i=1:n
        pivô=A[i,i]
        linha=A[i,:]
        coluna=(1/pivô)*A[:,i]
        L[:,i]=coluna #i-ésima coluna da L
        U[i,:]=linha #i-ésima linha da U
        A=A-coluna*linha'
    end
    return L,U
end

L,U = LU(A)
display(L)
display(U)

3×3 Matrix{Int64}:
 2   1   1
 4   5   4
 6  15  16

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 2.0  1.0  0.0
 3.0  4.0  1.0

3×3 Matrix{Float64}:
 2.0  1.0  1.0
 0.0  3.0  2.0
 0.0  0.0  5.0

3-element Vector{Float64}:
 0.5
 0.0
 0.0

3-element Vector{Float64}:
 -0.16666666666666666
  0.3333333333333333
  0.0

3-element Vector{Float64}:
 -0.03333333333333334
 -0.13333333333333333
  0.2

In [80]:
# 9-c), 9-d), 9-e)

e1 = [1
0
0]

e2 = [0
1
0]

e3 = [0
0
1]

x1 = U\e1
x2 = U\e2
x3 = U\e3

display(x1)
display(x2)
display(x3)

3-element Vector{Float64}:
 0.5
 0.0
 0.0

3-element Vector{Float64}:
 -0.16666666666666666
  0.3333333333333333
  0.0

3-element Vector{Float64}:
 -0.03333333333333334
 -0.13333333333333333
  0.2

In [83]:
# 9-f)

# A inversa B de A é tal que B*A*x1=e1, B*A*x2=e2, B*A*x3=e3.
# Calculando A*xi, que tem como resultado um vetor y, para achar a inversa B, basta resolvermos B*y=ei.
# Para as três equações mencionadas, a inversa de A deve dar o mesmo resultado.

y1 = A*x1
y2 = A*x2
y3 = A*x3

B


3-element Vector{Float64}:
 0.0
 0.0
 1.0